mysite/blog/urls.py
from django.urls import path
from .views import (
                    post_detail,
                    post_list,
                    PostListView,
                    post_share,
                    post_search,)
from .feeds import LatestPostsFeed

# we define an application namespace with the app_name variable (useful for URL patterns s.98)
app_name = 'blog'

urlpatterns = [
    path('', post_list, name='post_list'),
    # path('', PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
         post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', post_search, name='post_search'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')

]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset()\
                        .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250)
    """This is a field intended to be used in URLs. A slug is a
short label that contains only letters, numbers, underscores,
or hyphens. We will use the slug field to build beautiful, SEO friendly
URLs for our blog posts. We have added the
unique_for_date parameter to this field so that we can build
URLs for posts using their publish date and slug. Django will
prevent multiple posts from having the same slug for a
given date."""
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    """when user is deleted, the
  database will also delete its related blog posts"""
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               # This will allow us to access related objects easily.
                               related_name='blog_post')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    tags = TaggableManager()
    # The default manager.
    objects = models.Manager()
    # Our custom manager.
    published = PublishedManager()

    class Meta:
        """sort results in the publish field descending by default
         when we query the database"""
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    # return canonical URL for Post objects
    # we will use the reverse() method that allows you to build
    # URLs by their name and passing optional parameters.
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug],)


# related_name s.131
"""
After defining
this, we can retrieve the post of a comment object using comment.post
and retrieve all comments of a post using post.comments.all(). If
"""

class Comment(models.Model):
    # associate the comment with a single post.
    """related_name attribute allows us to name the attribute that we use for
the relation from the related object back to this one. After defining
this, we can retrieve the post of a comment object using comment.post
and retrieve all comments of a post using post.comments.all().If you
don't define the related_name attribute, Django will use the name of the
model in lowercase, followed by _set (that is, comment_set) to name the
manager of the related object back to this one."""
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # to deactivate inappropriate comments
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'test'
        # return f'Comment by {self.name} {self.post}'

mysite/blog/forms.py
from django import forms
from .models import Comment


class SearchForm(forms.Form):
    query = forms.CharField()


class EmailPostForm(forms.Form):
    # <input type="text">
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    '''The default widget can be overridden with the widget attribute.We
    use a Textarea widget to display it as a <textarea> HTML element
    instead of the default <input> element.'''
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        """to indicate which model we wanna use. By default, Django builds a form field for each field
        contained in the model. However, you can explicitly tell the
        framework which fields you want to include in your form using a
        fields list or define which fields you want to exclude using an exclude
        list of fields."""
        model = Comment
        fields = ('name', 'email', 'body')

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
# Django ORM aggregation function which allows to use Avg, Max....
from django.db.models import Count

# 3rd party libraries
from taggit.models import Tag

# local stuff
from .models import Post
from .forms import EmailPostForm, CommentForm, SearchForm


# s.186 Django 2 by Example
def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # results = Post.objects.annotate(search=SearchVector('title', 'body'),).filter(search=query)
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')
    return render(request, 'blog/post/search.html', {'form': form, 'query': query, 'results': results})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com',
                      [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


def post_list(request, tag_slug=None):

    """
        1. We instantiate the Paginator class with the number of objects
            we want to display on each page.
        2. We get the page GET parameter that indicates the current page
            number.
        3. We obtain the objects for the desired page calling the page()
            method of Paginator.
        4. If the page parameter is not an integer, we retrieve the first
            page of results. If this parameter is a number higher than
            the last page of results, we will retrieve the last page.
        5. We pass the page number and retrieved objects to the
            template."""

    """
    TAGS
    1. It takes an optional tag_slug parameter that has a None default value.
     This parameter will come in the URL.
    
    2. Inside the view, we build the initial QuerySet, retrieving all
    published posts, and if there is a given tag slug, we get the Tag
    object with the given slug using the get_object_or_404() shortcut.
    
    3. Then, we filter the list of posts by the ones that contain the
    given tag. Since this is a many-to-many relationship, we
    have to filter by tags contained in a given list, which, in our
    case, contains only one element.
"""
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get('page')

    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        for s in tag:
            print(s)
        # we filter the list of posts by the ones that contain
        # the given tag
        object_list = object_list.filter(tag__in=[tag])
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


class PostListView(ListView):
    print('PostListView get called')
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):

    # this function retrieves the object that matches given parameters or launches an HTTP 404
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    # List of active comments for this post. related_name == 'comments'
    comments = post.comments.filter(active=True)

    """We also use the same view to let our users add a new comment.
    Therefore, we initialize the new_comment variable by setting it to None."""
    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment we just created
            new_comment.post = post
            """By doing this, we are specifying that the new comment
            belongs to this post.
            Save the comment to the database"""
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    """
    1. We retrieve a Python list of IDs for the tags of the current
        post. The values_list() QuerySet returns tuples with the
        values for the given fields. We pass flat=True to it to get a flat
        list like [1, 2, 3, ...].
    2. We get all posts that contain any of these tags, excluding the
        current post itself.
    3. We use the Count aggregation function to generate a
        calculated field—same_tags—that contains the number of tags shared with all the tags queried.
    4. We order the result by the number of shared tags
        (descending order) and by publish to display recent posts first
        for the posts with the same number of shared tags. We slice
        the result to retrieve only the first four posts.
    """
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids) \
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')) \
                        .order_by('-same_tags', '-publish')[:4]


    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}

<h1>{{ post.title }}</h1>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown }}
<!--{{ post.body|linebreaks }}-->
<!--linebreaks converts the output into HTML line breaks.-->
<p>
    <a href="{% url "blog:post_share" post.id %}">
    Share this post
    </a>


  <h2>Similar posts</h2>
  {% for post in similar_posts %}
    <p>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
  {% empty %}
    There are no similar posts yet.
  {% endfor %}


    <!-- Django 2 by Example s.137 Django ORM-->
    {% with comments.count as total_comments %}
    <!--The 'with' template tag is useful to avoid hitting the database or
    accessing expensive methods multiple times.-->
<h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
</h2>
{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>There are no comments yet.</p>
{% endfor %}

<!--let's test this peace of code-->
{% if new_comment %}
{% else %}
<h2>Add a new comment</h2>
<form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>
{% endif %}
<h2>Your comment has been added.</h2>

{% endwith %}
</p>
{% endblock %}

mysite/blog/templates/blog/post/latest_posts.html
<ul>
{% for post in latest_posts %}
<li>
<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</li>
{% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
<h1>My Blog</h1>

{% if tag %}
<h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}

{% for post in posts %}
<h2>
<a href="{{ post.get_absolute_url }}">
{{ post.title }}
</a>
</h2>
<p class="tags">
    Tags:
    {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
<!--    {{ post.tags.all|join:", "}}-->
</p>
<p class="date">
Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|markdown|truncatewords_html:30 }}
<!--{{ post.body|truncatewords:30|linebreaks }}-->
{% endfor %}
<!--{% include "pagination.html" with page=posts %}-->
 {% include "pagination.html" with page=posts %}
{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}
{% block content %}
{% if query %}
<h1>Posts containing "{{ query }}"</h1>
<h3>
    {% with results.count as total_results %}
    Found {{ total_results }} result{{ total_results|pluralize }}
    {% endwith %}
</h3>
{% for post in results %}
<h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
{{ post.body|truncatewords:5 }}
{% empty %}
<p>There are no results for your query.</p>
{% endfor %}
<p><a href="{% url "blog:post_search" %}">Search again</a></p>
{% else %}
<h1>Search for posts</h1>
<form action="." method="get">
    {{ form.as_p }}
    <input type="submit" value="Search">
</form>
{% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
{% if sent %}
<h1>E-mail successfully sent</h1>
<p>
"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form action="." method="post">
{{ form.as_p }}
{% csrf_token %}
<input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}